name: Work 1 Renata
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
    - run: node --version
    - name: Print Something
      run: echo "Renata Tejeda Mercado"
    - name: Print Something 2
      run: echo "739500"